### ISSUE TITLE
Issue with HA 2023.8.B0

### ISSUE THREAD

**Issue by Thrasher2020** [pdw-mb/tsmart_ha#5]
Current beta has this issue:

`Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:619
Integration: Climate (documentation, issues)
First occurred: 09:05:01 (2 occurrences)
Last logged: 09:05:01

Error adding entities for domain climate with platform t_smart
Error while setting up t_smart platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'name_by_user'
`

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:619
Integration: Binary Sensor (documentation, issues)
First occurred: 09:05:01 (2 occurrences)
Last logged: 09:05:01

Error adding entities for domain binary_sensor with platform t_smart
Error while setting up t_smart platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'name_by_user'

**Comment by Thrasher2020** [comment]
HAOS 10.4

This issue only occurs after upgrade to 2023.8.b0 - I have rolled back to 2023.7.3 and everything goes back to normal (i.e. working).
